#OBJECT ORIENTED PROGRAMMING

In [1]:
import math
math.sqrt(36)

6.0

In [3]:
from math import sqrt as sq
sq(25)

5.0

In [5]:
import math as m
m.sqrt(144)

12.0

In [7]:
from math import *
sqrt(81)

9.0

In [9]:
import numpy as np

In [11]:
np.__version__

'2.0.1'

In [17]:
import pandas as pd

In [19]:
pd.__version__

'2.2.2'

#PRESS SHIFT + TAB TAB TAB TAB FOR MORE INFORMATION REGARDING SPECIFIC FUNCTION OR KEYWORD

https://docs.python.org/3/       
#Visit this site for more python keywords info.

#VECTORS



In [49]:
v = np.array([2,-6,8])
v


array([ 2, -6,  8])

In [51]:
type(v)

numpy.ndarray

#MATRIX


In [47]:
vec = np.array([[2,6,-9],[6,-9,7]])
vec

array([[ 2,  6, -9],
       [ 6, -9,  7]])

In [53]:
type(vec)

numpy.ndarray

#DATA SHAPES


In [57]:
v.shape

(3,)

In [59]:
vec.shape

(2, 3)

In [69]:
v.reshape(1,3)

array([[ 2, -6,  8]])

In [71]:
vec.reshape(3,2)

array([[ 2,  6],
       [-9,  6],
       [-9,  7]])

In [73]:
vec.reshape(2,3)

array([[ 2,  6, -9],
       [ 6, -9,  7]])

In [81]:
vec1 = np.array([[4,6,8],[7,1,1]])

In [87]:
t = np.array([vec,vec1])
t

array([[[ 2,  6, -9],
        [ 6, -9,  7]],

       [[ 4,  6,  8],
        [ 7,  1,  1]]])

In [89]:
t.shape

(2, 2, 3)

In [91]:
t.reshape(3,2,2)

array([[[ 2,  6],
        [-9,  6]],

       [[-9,  7],
        [ 4,  6]],

       [[ 8,  7],
        [ 1,  1]]])

In [95]:
t + 1

array([[[ 3,  7, -8],
        [ 7, -8,  8]],

       [[ 5,  7,  9],
        [ 8,  2,  2]]])

In [97]:
v + 1

array([ 3, -5,  9])

In [113]:
vec

array([[ 2,  6, -9],
       [ 6, -9,  7]])

In [115]:
vec.T

array([[ 2,  6],
       [ 6, -9],
       [-9,  7]])

In [131]:
v


array([ 2, -6,  8])

In [117]:
v.shape

(3,)

In [127]:
v2 = v.reshape(1,3)
v2

array([[ 2, -6,  8]])

In [129]:
v2.T

array([[ 2],
       [-6],
       [ 8]])

#SCALAR PRODUCT


In [139]:
x = np.array([1,6,7])
y = np.array([8,4,8])

In [145]:
print(np.dot(x,y))

88


In [143]:
x*y

array([ 8, 24, 56])

#MATRIX MULTIPLICATION RULE :- m*n . n*k = m*k
